<a href="https://colab.research.google.com/github/hermela-tt/afi-movie-game-solver/blob/main/afi-scrapper.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd

response = requests.get("https://afi.com", headers={"User-Agent": "Mozilla/5.0"})
print(response.status_code)

# ran 200

200

In [ ]:
soup = BeautifulSoup(response.text, "html.parser")
print(soup.title.text)

# ran American Film Institute

		American Film Institute

In [ ]:
#display the first 500 characters of webpage code
print(response.text[:500])

# ran <!DOCTYPE html>...

<!DOCTYPE html>
<html lang="en">
    <head><meta charset="UTF-8"><script type="text/javascript">(window.NREUM||(NREUM={})).init={privacy:{cookies_enabled:true},ajax:{deny_list:["bam.nr-data.net"]},distributed_tracing:{enabled:true}};(window.NREUM||(NREUM={})).loader_config={agentID:"1103240418",accountID:"3934328",trustKey:"66686",xpid:"Vw8EVVVRABABVFBaAgkPVlwF",licenseKey:"NRJS-93da15506e488dba2c8",applicationID:"1018588084",browserID:"1103240418"};;/*! For license information please see nr-l

In [ ]:
#look for standard link tags on page
links = soup.find_all("a")

#print the total number of links found
print(len(links))

# ran 183

183

In [ ]:
#loop through all 183 links found on the page
for link in links:
    #get the actual web address hidden inside the link
    href = link.get("href")

    #if the link exists and contains the word "picture" print
    if href and "picture" in href:
        print(href)

  # ran 3x https://www.afi.com/get-the-picture/

https://www.afi.com/get-the-picture/
https://www.afi.com/get-the-picture/
https://www.afi.com/get-the-picture
https://www.afi.com/get-the-picture/

In [ ]:
#get archive page and not main page
archive_response = requests.get("https://afi.com", headers={"User-Agent": "Mozilla/5.0"})

#read archive page layout
archive_soup = BeautifulSoup(archive_response.text, "html.parser")

#find all links on the archive page
archive_links = archive_soup.find_all("a")

#print first 20 links
for link in archive_links[:20]:
    href = link.get("href")
    if href:
        print(href)

#nope just general links

https://www.afi.com/
https://www.afi.com/home-page/
https://www.afi.com/about-afi/
https://www.afi.com/about-afi/#missionandvision
https://www.afi.com/equity-and-inclusion
/protect/
https://www.afi.com/history/
https://www.afi.com/board-of-trustees/
https://www.afi.com/senior-staff/
https://www.afi.com/impact/
https://www.afi.com/campus-access/
https://www.afi.com/afi-campus-access/#losangeles
https://www.afi.com/afi-campus-access/#silver
https://www.afi.com/contact/
https://www.afi.com/wp-login.php
https://shop.afi.com
/support/?Op=join
#
https://www.afi.com/support/
https://www.afi.com

In [ ]:
#try page 2
page2_response = requests.get("https://afi.com", headers={"User-Agent": "Mozilla/5.0"})
page2_soup = BeautifulSoup(page2_response.text, "html.parser")
page2_links = page2_soup.find_all("a")

for link in page2_links[:30]:
    href = link.get("href")
    if href:
        print(href)
#nope

https://www.afi.com/
https://www.afi.com/home-page/
https://www.afi.com/about-afi/
https://www.afi.com/about-afi/#missionandvision
https://www.afi.com/equity-and-inclusion
/protect/
https://www.afi.com/history/
https://www.afi.com/board-of-trustees/
https://www.afi.com/senior-staff/
https://www.afi.com/impact/
https://www.afi.com/campus-access/
https://www.afi.com/afi-campus-access/#losangeles
https://www.afi.com/afi-campus-access/#silver
https://www.afi.com/contact/
https://www.afi.com/wp-login.php
https://shop.afi.com
/support/?Op=join
#
https://www.afi.com/support/
https://www.afi.com
https://www.afi.com
#
https://conservatory.afi.com
https://conservatory.afi.com
https://conservatory.afi.com/innovative-programs
https://conservatory.afi.com/dww
https://conservatory.afi.com/admissions-requirements
https://conservatory.afi.com/alumni
https://watch.afi.com
https://conservatory.afi.com

In [ ]:
#check for hidden script frameworks or json data blocks on the main game page
live_response = requests.get("https://afi.com", headers={"User-Agent": "Mozilla/5.0"})
live_soup = BeautifulSoup(live_response.text, "html.parser")

#print all data container tags on the page
for tag in live_soup.find_all(attrs={"class": True})[:20]:
    print(tag.name, tag['class'])

# site runs on wordpress (ex: wp-singular)

body ['home', 'wp-singular', 'page-template', 'page-template-page-template', 'page-template-home-template-new26', 'page-template-page-templatehome-template-new26-php', 'page', 'page-id-72713', 'wp-theme-AFI', 'wpb-js-composer', 'js-comp-ver-8.7.4', 'vc_responsive']
div ['header_top']
div ['container']
div ['header_top_menu']
div ['menu-top-menu-container']
ul ['nav', 'navbar-nav']
li ['menu-item', 'menu-item-type-custom', 'menu-item-object-custom', 'current-menu-item', 'current_page_item', 'menu-item-home', 'menu-item-has-children', 'menu-item-11111']
ul ['sub-menu']
li ['menu-item', 'menu-item-type-post_type', 'menu-item-object-page', 'menu-item-14300']
li ['menu-item', 'menu-item-type-post_type', 'menu-item-object-page', 'menu-item-11112']
li ['aboutitem', 'menu-item', 'menu-item-type-custom', 'menu-item-object-custom', 'menu-item-36308']
li ['aboutitem', 'menu-item', 'menu-item-type-custom', 'menu-item-object-custom', 'menu-item-36309']
li ['menu-item', 'menu-item-type-custom', 'menu-item-object-custom', 'menu-item-43135']
li ['menu-item', 'menu-item-type-post_type', 'menu-item-object-page', 'menu-item-11113']
li ['menu-item', 'menu-item-type-post_type', 'menu-item-object-page', 'menu-item-11115']
li ['menu-item', 'menu-item-type-post_type', 'menu-item-object-page', 'menu-item-11116']
li ['menu-item', 'menu-item-type-custom', 'menu-item-object-custom', 'menu-item-25447']
li ['menu-item', 'menu-item-type-post_type', 'menu-item-object-page', 'menu-item-11118']
li ['aboutitem', 'menu-item', 'menu-item-type-custom', 'menu-item-object-custom', 'menu-item-67878']
li ['aboutitem', 'menu-item', 'menu-item-type-custom', 'menu-item-object-custom', 'menu-item-67876']

In [ ]:
#get day directly using the directory pattern
game_response = requests.get("https://www.afi.com/movie-games/500/", headers={"User-Agent": "Mozilla/5.0"})
game_soup = BeautifulSoup(game_response.text, "html.parser")

# print the page header to verify we reached the right game
print(game_soup.find("h2").text if game_soup.find("h2") else "Header not found")

#ran Get the Picture

Get the Picture

In [ ]:
#fetchdata for day 1000
test_response = requests.get("https://afi.com", headers={"User-Agent": "Mozilla/5.0"})
test_soup = BeautifulSoup(test_response.text, "html.parser")

#print text found on page to find the movie options
for tag in test_soup.find_all(["li", "button", "div"])[:40]:
    text = tag.text.strip()
    if text:
        print(f"{tag.name}:{text}")

#printed too much

div:AFI

AFI Home
About AFI
MISSION AND VISION
EQUITY AND INCLUSION
Protect
History
Board of Trustees
Senior Staff
Impact Report
Afi Campus Access
Los Angeles
Silver
Contact


Log In
Shop
JOIN

Support
div:AFI

AFI Home
About AFI
MISSION AND VISION
EQUITY AND INCLUSION
Protect
History
Board of Trustees
Senior Staff
Impact Report
Afi Campus Access
Los Angeles
Silver
Contact


Log In
Shop
JOIN

Support
div:AFI

AFI Home
About AFI
MISSION AND VISION
EQUITY AND INCLUSION
Protect
History
Board of Trustees
Senior Staff
Impact Report
Afi Campus Access
Los Angeles
Silver
Contact


Log In
Shop
JOIN

Support
div:AFI

AFI Home
About AFI
MISSION AND VISION
EQUITY AND INCLUSION
Protect
History
Board of Trustees
Senior Staff
Impact Report
Afi Campus Access
Los Angeles
Silver
Contact


Log In
Shop
JOIN

Support
li:AFI

AFI Home
About AFI
MISSION AND VISION
EQUITY AND INCLUSION
Protect
History
Board of Trustees
Senior Staff
Impact Report
Afi Campus Access
Los Angeles
Silver
Contact
li:AFI Home
li:About AFI
li:MISSION AND VISION
li:EQUITY AND INCLUSION
li:Protect
li:History
li:Board of Trustees
li:Senior Staff
li:Impact Report
li:Afi Campus Access
li:Los Angeles
li:Silver
li:Contact
li:Log In
li:Shop
li:JOIN
li:Support
div:AMERICAN FILM INSTITUTE





AMERICAN FILM INSTITUTE




OUR WORK

CONSERVATORY

Masters Degree Program
Innovative Programs
DWW+
Admissions
Alumni
Watch Thesis Films
Campus


FESTIVALS

AFI FEST
AFI Silver Theatre and Cultural Center


AWARDS

AFI Life Achievement Award
AFI Awards


AFI MOVIE CLUB

Get the Picture Daily Game


PRESERVATION

AFI Catalog of Feature Films
AFI Archive
AFI Collection at the Library of Congress
The Robert Osborne Collection


LISTS

AFI’S 100 YEARS…100 MOVIES — 10TH ANNIVERSARY EDITION
AFI’s 100 YEARS…100 MOVIE QUOTES
AFI Lists


AFI SILVER THEATRE

AFI Silver Theatre and Cultural Center


SUPPORT

Donate
Become a Member
Partner Opportunities
Other Ways to Give
Member Portal
Impact Report


AFI

News
Press
Newsletter Sign-up


INNOVATIVE PROGRAMS

DWW+
Cinematography Intensive Workshop




FILM SCHOOL

AFI CONSERVATORY HOME

MFA PROGRAM
Cinematography
Directing
Editing
Producing
Production Design
Screenwriting


ADMISSIONS
ALUMNI
CAMPUS
WATCH
ABOUT
Commencement
DONATE


EVENTS

AFI Life Achievement Award
AFI AWARDS
AFI FEST
AFI Silver Theatre & Cultural Center


LISTS

TOP 100 MOVIES
TOP 100 QUOTES
TOP 100 MUSICALS
Top Westerns
TOP 100 LAUGHS
TOP 100 PASSIONS
View all lists


NEWS

AFI Newsletter
Inside the Conservatory
Alumni Projects
Watch AFI Films
News
Press





DONATE
div:AMERICAN FILM INSTITUTE





AMERICAN FILM INSTITUTE




OUR WORK

CONSERVATORY

Masters Degree Program
Innovative Programs
DWW+
Admissions
Alumni
Watch Thesis Films
Campus


FESTIVALS

AFI FEST
AFI Silver Theatre and Cultural Center


AWARDS

AFI Life Achievement Award
AFI Awards


AFI MOVIE CLUB

Get the Picture Daily Game


PRESERVATION

AFI Catalog of Feature Films
AFI Archive
AFI Collection at the Library of Congress
The Robert Osborne Collection


LISTS

AFI’S 100 YEARS…100 MOVIES — 10TH ANNIVERSARY EDITION
AFI’s 100 YEARS…100 MOVIE QUOTES
AFI Lists


AFI SILVER THEATRE

AFI Silver Theatre and Cultural Center


SUPPORT

Donate
Become a Member
Partner Opportunities
Other Ways to Give
Member Portal
Impact Report


AFI

News
Press
Newsletter Sign-up


INNOVATIVE PROGRAMS

DWW+
Cinematography Intensive Workshop




FILM SCHOOL

AFI CONSERVATORY HOME

MFA PROGRAM
Cinematography
Directing
Editing
Producing
Production Design
Screenwriting


ADMISSIONS
ALUMNI
CAMPUS
WATCH
ABOUT
Commencement
DONATE


EVENTS

AFI Life Achievement Award
AFI AWARDS
AFI FEST
AFI Silver Theatre & Cultural Center


LISTS

TOP 100 MOVIES
TOP 100 QUOTES
TOP 100 MUSICALS
Top Westerns
TOP 100 LAUGHS
TOP 100 PASSIONS
View all lists


NEWS

AFI Newsletter
Inside the Conservatory
Alumni Projects
Watch AFI Films
News
Press





DONATE
div:AMERICAN FILM INSTITUTE





AMERICAN FILM INSTITUTE
div:AMERICAN FILM INSTITUTE
div:AMERICAN FILM INSTITUTE
div:OUR WORK

CONSERVATORY

Masters Degree Program
Innovative Programs
DWW+
Admissions
Alumni
Watch Thesis Films
Campus


FESTIVALS

AFI FEST
AFI Silver Theatre and Cultural Center


AWARDS

AFI Life Achievement Award
AFI Awards


AFI MOVIE CLUB

Get the Picture Daily Game


PRESERVATION

AFI Catalog of Feature Films
AFI Archive
AFI Collection at the Library of Congress
The Robert Osborne Collection


LISTS

AFI’S 100 YEARS…100 MOVIES — 10TH ANNIVERSARY EDITION
AFI’s 100 YEARS…100 MOVIE QUOTES
AFI Lists


AFI SILVER THEATRE

AFI Silver Theatre and Cultural Center


SUPPORT

Donate
Become a Member
Partner Opportunities
Other Ways to Give
Member Portal
Impact Report


AFI

News
Press
Newsletter Sign-up


INNOVATIVE PROGRAMS

DWW+
Cinematography Intensive Workshop




FILM SCHOOL

AFI CONSERVATORY HOME

MFA PROGRAM
Cinematography
Directing
Editing
Producing
Production Design
Screenwriting


ADMISSIONS
ALUMNI
CAMPUS
WATCH
ABOUT
Commencement
DONATE


EVENTS

AFI Life Achievement Award
AFI AWARDS
AFI FEST
AFI Silver Theatre & Cultural Center


LISTS

TOP 100 MOVIES
TOP 100 QUOTES
TOP 100 MUSICALS
Top Westerns
TOP 100 LAUGHS
TOP 100 PASSIONS
View all lists


NEWS

AFI Newsletter
Inside the Conservatory
Alumni Projects
Watch AFI Films
News
Press
li:OUR WORK

CONSERVATORY

Masters Degree Program
Innovative Programs
DWW+
Admissions
Alumni
Watch Thesis Films
Campus


FESTIVALS

AFI FEST
AFI Silver Theatre and Cultural Center


AWARDS

AFI Life Achievement Award
AFI Awards


AFI MOVIE CLUB

Get the Picture Daily Game


PRESERVATION

AFI Catalog of Feature Films
AFI Archive
AFI Collection at the Library of Congress
The Robert Osborne Collection


LISTS

AFI’S 100 YEARS…100 MOVIES — 10TH ANNIVERSARY EDITION
AFI’s 100 YEARS…100 MOVIE QUOTES
AFI Lists


AFI SILVER THEATRE

AFI Silver Theatre and Cultural Center


SUPPORT

Donate
Become a Member
Partner Opportunities
Other Ways to Give
Member Portal
Impact Report


AFI

News
Press
Newsletter Sign-up


INNOVATIVE PROGRAMS

DWW+
Cinematography Intensive Workshop
li:CONSERVATORY

Masters Degree Program
Innovative Programs
DWW+
Admissions
Alumni
Watch Thesis Films
Campus
li:Masters Degree Program
li:Innovative Programs
li:DWW+
li:Admissions
li:Alumni
li:Watch Thesis Films

In [ ]:
#get data for day 1000
test_response = requests.get("https://afi.com", headers={"User-Agent": "Mozilla/5.0"})
test_soup = BeautifulSoup(test_response.text, "html.parser")

#search the entire page layout for text or image
for tag in test_soup.find_all(["li", "img", "h3", "h4"]):
    text = tag.text.strip()
    #check if the element is the game image
    if tag.name == "img" and "gtp" in str(tag.get("class")):
        print(f"img:{tag.get('src')}")
    #check if the element holds the movie choice data
    elif "Guess the movie" in text or (tag.name == "li" and text.isupper()):
        print(f"{tag.name}:{text}")

# ran a bunch of stuff i dont need, just general navigation and footer info

li:MISSION AND VISION
li:EQUITY AND INCLUSION
li:JOIN
li:DWW+
li:AFI FEST
li:AFI’S 100 YEARS…100 MOVIES — 10TH ANNIVERSARY EDITION
li:DWW+
li:MFA PROGRAM
li:ADMISSIONS
li:ALUMNI
li:CAMPUS
li:WATCH
li:ABOUT
li:DONATE
li:AFI AWARDS
li:AFI FEST
li:TOP 100 MOVIES
li:TOP 100 QUOTES
li:TOP 100 MUSICALS
li:TOP 100 LAUGHS
li:TOP 100 PASSIONS
li:AFI DWW+
li:AFI FEST
li:AFI AWARDS
li:CAREERS
li:PRESS
li:NEWS
li:VIDEOS

In [ ]:
#get day 1000
test_response = requests.get("https://afi.com", headers={"User-Agent": "Mozilla/5.0"})
test_soup = BeautifulSoup(test_response.text, "html.parser")

#look for all interactive button tags on the page
for button in test_soup.find_all("button"):
    button_text = button.text.strip()
    if button_text:
        print(f"button:{button_text}")

#look for all imgs to isolate film still
for img in test_soup.find_all("img"):
    img_src = img.get("src")
    #check if the image belongs to the game upload folder
    if img_src and "wp-content/uploads" in img_src:
        print(f"img:{img_src}")

# ran info on buttons like cookie and privacy info

button:OK
button:Accept
button:Close GDPR Cookie Settings
button:Privacy Overview
button:Strictly Necessary Cookies
button:Enable All
button:Save Changes

In [ ]:
#fetch the webpage data for game number 1000
test_response = requests.get("https://afi.com", headers={"User-Agent": "Mozilla/5.0"})
test_soup = BeautifulSoup(test_response.text, "html.parser")

#search the entire body text to pull out lines near the game prompt
page_text = test_soup.get_text(separator="\n", strip=True)
for line in page_text.split("\n"):
    if "Guess the movie" in line:
        print(line)

# prints nothing

In [ ]:
#use email marketing campaign url parameters
email_url = "https://afi.com"
response = requests.get(email_url, headers={"User-Agent": "Mozilla/5.0"})
soup = BeautifulSoup(response.text, "html.parser")

#print out lines that contain  text options
for tag in soup.find_all(["div", "p", "button"]):
    text = tag.text.strip()
    if text and any(word in text for word in ["Guess", "Before", "Hugo"]):
        print(f"{tag.name}:{text}")

In [ ]:
# find the hidden backend data for the game
api_url = "https://afi.com"
response = requests.get(api_url, headers={"User-Agent": "Mozilla/5.0"})

# display the raw backend text data
print(response.text)

<!DOCTYPE html>
<html lang="en">
    <head><meta charset="UTF-8"><script>if(navigator.userAgent.match(/MSIE|Internet Explorer/i)||navigator.userAgent.match(/Trident\/7\..*?rv:11/i)){var href=document.location.href;if(!href.match(/[?&]nowprocket/)){if(href.indexOf("?")==-1){if(href.indexOf("#")==-1){document.location.href=href+"?nowprocket=1"}else{document.location.href=href.replace("#","?nowprocket=1#")}}else{if(href.indexOf("#")==-1){document.location.href=href+"&nowprocket=1"}else{document.location.href=href.replace("#","&nowprocket=1#")}}}}</script><script>(()=>{class RocketLazyLoadScripts{constructor(){this.v="2.0.5",this.userEvents=["keydown","keyup","mousedown","mouseup","mousemove","mouseover","mouseout","touchmove","touchstart","touchend","touchcancel","wheel","click","dblclick","input"],this.attributeEvents=["onblur","onclick","oncontextmenu","ondblclick","onfocus","onmousedown","onmouseenter","onmouseleave","onmousemove","onmouseout","onmouseover","onmouseup","onmousewheel","onscroll","onsubmit"]}async t(){this.i(),this.o(),/iP(ad|hone)/.test(navigator.userAgent)&&this.h(),this.u(),this.l(this),this.m(),this.k(this),this.p(this),this._(),await Promise.all([this.R(),this.L()]),this.lastBreath=Date.now(),this.S(this),this.P(),this.D(),this.O(),this.M(),await this.C(this.delayedScripts.normal),await this.C(this.delayedScripts.defer),await this.C(this.delayedScripts.async),await this.T(),await this.F(),await this.j(),await this.A(),window.dispatchEvent(new Event("rocket-allScriptsLoaded")),this.everythingLoaded=!0,this.lastTouchEnd&&await new Promise(t=>setTimeout(t,500-Date.now()+this.lastTouchEnd)),this.I(),this.H(),this.U(),this.W()}i(){this.CSPIssue=sessionStorage.getItem("rocketCSPIssue"),document.addEventListener("securitypolicyviolation",t=>{this.CSPIssue||"script-src-elem"!==t.violatedDirective||"data"!==t.blockedURI||(this.CSPIssue=!0,sessionStorage.setItem("rocketCSPIssue",!0))},{isRocket:!0})}o(){window.addEventListener("pageshow",t=>{this.persisted=t.persisted,this.realWindowLoadedFired=!0},{isRocket:!0}),window.addEventListener("pagehide",()=>{this.onFirstUserAction=null},{isRocket:!0})}h(){let t;function e(e){t=e}window.addEventListener("touchstart",e,{isRocket:!0}),window.addEventListener("touchend",function i(o){o.changedTouches[0]&&t.changedTouches[0]&&Math.abs(o.changedTouches[0].pageX-t.changedTouches[0].pageX)<10&&Math.abs(o.changedTouches[0].pageY-t.changedTouches[0].pageY)<10&&o.timeStamp-t.timeStamp<200&&(window.removeEventListener("touchstart",e,{isRocket:!0}),window.removeEventListener("touchend",i,{isRocket:!0}),"INPUT"===o.target.tagName&&"text"===o.target.type||(o.target.dispatchEvent(new TouchEvent("touchend",{target:o.target,bubbles:!0})),o.target.dispatchEvent(new MouseEvent("mouseover",{target:o.target,bubbles:!0})),o.target.dispatchEvent(new PointerEvent("click",{target:o.target,bubbles:!0,cancelable:!0,detail:1,clientX:o.changedTouches[0].clientX,clientY:o.changedTouches[0].clientY})),event.preventDefault()))},{isRocket:!0})}q(t){this.userActionTriggered||("mousemove"!==t.type||this.firstMousemoveIgnored?"keyup"===t.type||"mouseover"===t.type||"mouseout"===t.type||(this.userActionTriggered=!0,this.onFirstUserAction&&this.onFirstUserAction()):this.firstMousemoveIgnored=!0),"click"===t.type&&t.preventDefault(),t.stopPropagation(),t.stopImmediatePropagation(),"touchstart"===this.lastEvent&&"touchend"===t.type&&(this.lastTouchEnd=Date.now()),"click"===t.type&&(this.lastTouchEnd=0),this.lastEvent=t.type,t.composedPath&&t.composedPath()[0].getRootNode()instanceof ShadowRoot&&(t.rocketTarget=t.composedPath()[0]),this.savedUserEvents.push(t)}u(){this.savedUserEvents=[],this.userEventHandler=this.q.bind(this),this.userEvents.forEach(t=>window.addEventListener(t,this.userEventHandler,{passive:!1,isRocket:!0})),document.addEventListener("visibilitychange",this.userEventHandler,{isRocket:!0})}U(){this.userEvents.forEach(t=>window.removeEventListener(t,this.userEventHandler,{passive:!1,isRocket:!0})),document.removeEventListener("visibilitychange",this.userEventHandler,{isRocket:!0}),this.savedUserEvents.forEach(t=>{(t.rocketTarget||t.target).dispatchEvent(new window[t.constructor.name](t.type,t))})}m(){const t="return false",e=Array.from(this.attributeEvents,t=>"data-rocket-"+t),i="["+this.attributeEvents.join("],[")+"]",o="[data-rocket-"+this.attributeEvents.join("],[data-rocket-")+"]",s=(e,i,o)=>{o&&o!==t&&(e.setAttribute("data-rocket-"+i,o),e["rocket"+i]=new Function("event",o),e.setAttribute(i,t))};new MutationObserver(t=>{for(const n of t)"attributes"===n.type&&(n.attributeName.startsWith("data-rocket-")||this.everythingLoaded?n.attributeName.startsWith("data-rocket-")&&this.everythingLoaded&&this.N(n.target,n.attributeName.substring(12)):s(n.target,n.attributeName,n.target.getAttribute(n.attributeName))),"childList"===n.type&&n.addedNodes.forEach(t=>{if(t.nodeType===Node.ELEMENT_NODE)if(this.everythingLoaded)for(const i of[t,...t.querySelectorAll(o)])for(const t of i.getAttributeNames())e.includes(t)&&this.N(i,t.substring(12));else for(const e of[t,...t.querySelectorAll(i)])for(const t of e.getAttributeNames())this.attributeEvents.includes(t)&&s(e,t,e.getAttribute(t))})}).observe(document,{subtree:!0,childList:!0,attributeFilter:[...this.attributeEvents,...e]})}I(){this.attributeEvents.forEach(t=>{document.querySelectorAll("[data-rocket-"+t+"]").forEach(e=>{this.N(e,t)})})}N(t,e){const i=t.getAttribute("data-rocket-"+e);i&&(t.setAttribute(e,i),t.removeAttribute("data-rocket-"+e))}k(t){Object.defineProperty(HTMLElement.prototype,"onclick",{get(){return this.rocketonclick||null},set(e){this.rocketonclick=e,this.setAttribute(t.everythingLoaded?"onclick":"data-rocket-onclick","this.rocketonclick(event)")}})}S(t){function e(e,i){let o=e[i];e[i]=null,Object.defineProperty(e,i,{get:()=>o,set(s){t.everythingLoaded?o=s:e["rocket"+i]=o=s}})}e(document,"onreadystatechange"),e(window,"onload"),e(window,"onpageshow");try{Object.defineProperty(document,"readyState",{get:()=>t.rocketReadyState,set(e){t.rocketReadyState=e},configurable:!0}),document.readyState="loading"}catch(t){console.log("WPRocket DJE readyState conflict, bypassing")}}l(t){this.originalAddEventListener=EventTarget.prototype.addEventListener,this.originalRemoveEventListener=EventTarget.prototype.removeEventListener,this.savedEventListeners=[],EventTarget.prototype.addEventListener=function(e,i,o){o&&o.isRocket||!t.B(e,this)&&!t.userEvents.includes(e)||t.B(e,this)&&!t.userActionTriggered||e.startsWith("rocket-")||t.everythingLoaded?t.originalAddEventListener.call(this,e,i,o):(t.savedEventListeners.push({target:this,remove:!1,type:e,func:i,options:o}),"mouseenter"!==e&&"mouseleave"!==e||t.originalAddEventListener.call(this,e,t.savedUserEvents.push,o))},EventTarget.prototype.removeEventListener=function(e,i,o){o&&o.isRocket||!t.B(e,this)&&!t.userEvents.includes(e)||t.B(e,this)&&!t.userActionTriggered||e.startsWith("rocket-")||t.everythingLoaded?t.originalRemoveEventListener.call(this,e,i,o):t.savedEventListeners.push({target:this,remove:!0,type:e,func:i,options:o})}}J(t,e){this.savedEventListeners=this.savedEventListeners.filter(i=>{let o=i.type,s=i.target||window;return e!==o||t!==s||(this.B(o,s)&&(i.type="rocket-"+o),this.$(i),!1)})}H(){EventTarget.prototype.addEventListener=this.originalAddEventListener,EventTarget.prototype.removeEventListener=this.originalRemoveEventListener,this.savedEventListeners.forEach(t=>this.$(t))}$(t){t.remove?this.originalRemoveEventListener.call(t.target,t.type,t.func,t.options):this.originalAddEventListener.call(t.target,t.type,t.func,t.options)}p(t){let e;function i(e){return t.everythingLoaded?e:e.split(" ").map(t=>"load"===t||t.startsWith("load.")?"rocket-jquery-load":t).join(" ")}function o(o){function s(e){const s=o.fn[e];o.fn[e]=o.fn.init.prototype[e]=function(){return this[0]===window&&t.userActionTriggered&&("string"==typeof arguments[0]||arguments[0]instanceof String?arguments[0]=i(arguments[0]):"object"==typeof arguments[0]&&Object.keys(arguments[0]).forEach(t=>{const e=arguments[0][t];delete arguments[0][t],arguments[0][i(t)]=e})),s.apply(this,arguments),this}}if(o&&o.fn&&!t.allJQueries.includes(o)){const e={DOMContentLoaded:[],"rocket-DOMContentLoaded":[]};for(const t in e)document.addEventListener(t,()=>{e[t].forEach(t=>t())},{isRocket:!0});o.fn.ready=o.fn.init.prototype.ready=function(i){function s(){parseInt(o.fn.jquery)>2?setTimeout(()=>i.bind(document)(o)):i.bind(document)(o)}return"function"==typeof i&&(t.realDomReadyFired?!t.userActionTriggered||t.fauxDomReadyFired?s():e["rocket-DOMContentLoaded"].push(s):e.DOMContentLoaded.push(s)),this},s("on"),s("one"),s("off"),t.allJQueries.push(o)}e=o}t.allJQueries=[],o(window.jQuery),Object.defineProperty(window,"jQuery",{get:()=>e,set(t){o(t)}})}P(){const t=new Map;document.write=document.writeln=function(e){const i=document.currentScript,o=document.createRange(),s=i.parentElement;let n=t.get(i);void 0===n&&(n=i.nextSibling,t.set(i,n));const c=document.createDocumentFragment();o.setStart(c,0),c.appendChild(o.createContextualFragment(e)),s.insertBefore(c,n)}}async R(){return new Promise(t=>{this.userActionTriggered?t():this.onFirstUserAction=t})}async L(){return new Promise(t=>{document.addEventListener("DOMContentLoaded",()=>{this.realDomReadyFired=!0,t()},{isRocket:!0})})}async j(){return this.realWindowLoadedFired?Promise.resolve():new Promise(t=>{window.addEventListener("load",t,{isRocket:!0})})}M(){this.pendingScripts=[];this.scriptsMutationObserver=new MutationObserver(t=>{for(const e of t)e.addedNodes.forEach(t=>{"SCRIPT"!==t.tagName||!t.src||t.noModule||t.isWPRocket||this.pendingScripts.push({script:t,promise:new Promise(e=>{const i=()=>{const i=this.pendingScripts.findIndex(e=>e.script===t);i>=0&&this.pendingScripts.splice(i,1),e()};t.addEventListener("load",i,{isRocket:!0}),t.addEventListener("error",i,{isRocket:!0}),setTimeout(i,1e3)})})})}),this.scriptsMutationObserver.observe(document,{childList:!0,subtree:!0})}async F(){await this.X(),this.pendingScripts.length?(await this.pendingScripts[0].promise,await this.F()):this.scriptsMutationObserver.disconnect()}D(){this.delayedScripts={normal:[],async:[],defer:[]},document.querySelectorAll("script[type$=rocketlazyloadscript]").forEach(t=>{t.hasAttribute("data-rocket-src")?t.hasAttribute("async")&&!1!==t.async?this.delayedScripts.async.push(t):t.hasAttribute("defer")&&!1!==t.defer||"module"===t.getAttribute("data-rocket-type")?this.delayedScripts.defer.push(t):this.delayedScripts.normal.push(t):this.delayedScripts.normal.push(t)})}async _(){await this.L();let t=[];document.querySelectorAll("script[type$=rocketlazyloadscript][data-rocket-src]").forEach(e=>{let i=e.getAttribute("data-rocket-src");if(i&&!i.startsWith("data:")){i.startsWith("//")&&(i=location.protocol+i);try{const o=new URL(i).origin;o!==location.origin&&t.push({src:o,crossOrigin:e.crossOrigin||"module"===e.getAttribute("data-rocket-type")})}catch(t){}}}),t=[...new Map(t.map(t=>[JSON.stringify(t),t])).values()],this.Y(t,"preconnect")}async G(t){if(await this.K(),!0!==t.noModule||!("noModule"in HTMLScriptElement.prototype))return new Promise(e=>{let i;function o(){(i||t).setAttribute("data-rocket-status","executed"),e()}try{if(navigator.userAgent.includes("Firefox/")||""===navigator.vendor||this.CSPIssue)i=document.createElement("script"),[...t.attributes].forEach(t=>{let e=t.nodeName;"type"!==e&&("data-rocket-type"===e&&(e="type"),"data-rocket-src"===e&&(e="src"),i.setAttribute(e,t.nodeValue))}),t.text&&(i.text=t.text),t.nonce&&(i.nonce=t.nonce),i.hasAttribute("src")?(i.addEventListener("load",o,{isRocket:!0}),i.addEventListener("error",()=>{i.setAttribute("data-rocket-status","failed-network"),e()},{isRocket:!0}),setTimeout(()=>{i.isConnected||e()},1)):(i.text=t.text,o()),i.isWPRocket=!0,t.parentNode.replaceChild(i,t);else{const i=t.getAttribute("data-rocket-type"),s=t.getAttribute("data-rocket-src");i?(t.type=i,t.removeAttribute("data-rocket-type")):t.removeAttribute("type"),t.addEventListener("load",o,{isRocket:!0}),t.addEventListener("error",i=>{this.CSPIssue&&i.target.src.startsWith("data:")?(console.log("WPRocket: CSP fallback activated"),t.removeAttribute("src"),this.G(t).then(e)):(t.setAttribute("data-rocket-status","failed-network"),e())},{isRocket:!0}),s?(t.fetchPriority="high",t.removeAttribute("data-rocket-src"),t.src=s):t.src="data:text/javascript;base64,"+window.btoa(unescape(encodeURIComponent(t.text)))}}catch(i){t.setAttribute("data-rocket-status","failed-transform"),e()}});t.setAttribute("data-rocket-status","skipped")}async C(t){const e=t.shift();return e?(e.isConnected&&await this.G(e),this.C(t)):Promise.resolve()}O(){this.Y([...this.delayedScripts.normal,...this.delayedScripts.defer,...this.delayedScripts.async],"preload")}Y(t,e){this.trash=this.trash||[];let i=!0;var o=document.createDocumentFragment();t.forEach(t=>{const s=t.getAttribute&&t.getAttribute("data-rocket-src")||t.src;if(s&&!s.startsWith("data:")){const n=document.createElement("link");n.href=s,n.rel=e,"preconnect"!==e&&(n.as="script",n.fetchPriority=i?"high":"low"),t.getAttribute&&"module"===t.getAttribute("data-rocket-type")&&(n.crossOrigin=!0),t.crossOrigin&&(n.crossOrigin=t.crossOrigin),t.integrity&&(n.integrity=t.integrity),t.nonce&&(n.nonce=t.nonce),o.appendChild(n),this.trash.push(n),i=!1}}),document.head.appendChild(o)}W(){this.trash.forEach(t=>t.remove())}async T(){try{document.readyState="interactive"}catch(t){}this.fauxDomReadyFired=!0;try{await this.K(),this.J(document,"readystatechange"),document.dispatchEvent(new Event("rocket-readystatechange")),await this.K(),document.rocketonreadystatechange&&document.rocketonreadystatechange(),await this.K(),this.J(document,"DOMContentLoaded"),document.dispatchEvent(new Event("rocket-DOMContentLoaded")),await this.K(),this.J(window,"DOMContentLoaded"),window.dispatchEvent(new Event("rocket-DOMContentLoaded"))}catch(t){console.error(t)}}async A(){try{document.readyState="complete"}catch(t){}try{await this.K(),this.J(document,"readystatechange"),document.dispatchEvent(new Event("rocket-readystatechange")),await this.K(),document.rocketonreadystatechange&&document.rocketonreadystatechange(),await this.K(),this.J(window,"load"),window.dispatchEvent(new Event("rocket-load")),await this.K(),window.rocketonload&&window.rocketonload(),await this.K(),this.allJQueries.forEach(t=>t(window).trigger("rocket-jquery-load")),await this.K(),this.J(window,"pageshow");const t=new Event("rocket-pageshow");t.persisted=this.persisted,window.dispatchEvent(t),await this.K(),window.rocketonpageshow&&window.rocketonpageshow({persisted:this.persisted})}catch(t){console.error(t)}}async K(){Date.now()-this.lastBreath>45&&(await this.X(),this.lastBreath=Date.now())}async X(){return document.hidden?new Promise(t=>setTimeout(t)):new Promise(t=>requestAnimationFrame(t))}B(t,e=window){return e===document&&"readystatechange"===t||(e===document&&"DOMContentLoaded"===t||(e===window&&"DOMContentLoaded"===t||(e===window&&"load"===t||e===window&&"pageshow"===t)))}static run(){(new RocketLazyLoadScripts).t()}}RocketLazyLoadScripts.run()})();
</script>

        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>
		American Film Institute
		</title>
<link data-rocket-prefetch href="https://fonts.googleapis.com" rel="dns-prefetch">
<link data-rocket-prefetch href="https://use.typekit.net" rel="dns-prefetch">
<link data-rocket-prefetch href="https://cdnjs.cloudflare.com" rel="dns-prefetch">
<link data-rocket-prefetch href="https://challenges.cloudflare.com" rel="dns-prefetch">
<link data-rocket-preload as="style" href="https://fonts.googleapis.com/css?family=Roboto%3A300%2C400&#038;display=swap" rel="preload">
<link href="https://fonts.googleapis.com/css?family=Roboto%3A300%2C400&#038;display=swap" media="print" onload="this.media=&#039;all&#039;" rel="stylesheet">
<noscript data-wpr-hosted-gf-parameters=""><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto%3A300%2C400&#038;display=swap"></noscript><link rel="preload" data-rocket-preload as="image" href="https://prdaficalmjediwestussa.blob.core.windows.net/images/2026/05/AFI26-Home-Heros-desk-LAAEddie4.webp" media="(orientation: landscape) and (min-width: 1200px) and (-webkit-min-device-pixel-ratio: 1.5),(orientation: portrait) and (min-width: 993px) and (-webkit-min-device-pixel-ratio: 1.5)" fetchpriority="high"><link rel="preload" data-rocket-preload as="image" href="https://prdaficalmjediwestussa.blob.core.windows.net/images/2026/06/AFI26-Home-Heros-mob-AFIv3.webp" media="(orientation: landscape) and (max-width: 900px),(orientation: portrait) and (max-width: 576px)" fetchpriority="high"><link rel="preload" data-rocket-preload as="image" href="https://prdaficalmjediwestussa.blob.core.windows.net/images/2026/05/AFI26-Home-Heros-tab-LAAEddie5.webp" media="(orientation: landscape) and (max-width: 1199px) and (min-width: 901px),(orientation: portrait) and (max-width: 992px) and (min-width: 577px)" fetchpriority="high"><link rel="preload" data-rocket-preload as="image" href="https://prdaficalmjediwestussa.blob.core.windows.net/images/2026/05/AFI26-Home-Heros-desk-LAAEddie4.webp" media="(min-width: 1199.1px)" fetchpriority="high">
		<meta name="description" content="Homepage 2026





[vc_se" />
				<meta property="og:title" content="Homepage 2026"/>
						<meta name="robots" content="index" />
				<meta http-equiv="Content-Type" content="text/html" />
		<meta name="twitter:card" content="summary_large_image" />

		<meta data-n-head="ssr" data-hid="og:image:type" property="og:image:type" content="image/jpeg">
		<meta property="og:locale" content="en_US" />
		<meta property="og:site_name" content="American Film Institute" />
		<meta property="og:type" content="article" />
		<meta property="og:title" content="American Film Institute" />
		<meta property="og:url" content="https://www.afi.com/" />
		<meta name="twitter:card" content="summary_large_image" />
		<meta name="twitter:site" content="American Film Institute" />
		<meta name="twitter:title" content="American Film Institute" />
		<meta name="twitter:description" content="" />
		<meta name="twitter:creator" content="@afifilm" />
		<meta property="og:image:width" content="1200" />
		<meta property="og:image:height" content="630" />


                        <meta property="og:description" content="">
        <meta property="og:image" content="https://www.afi.com/images/afi-social.jpg">
        <meta name="twitter:image" content="https://www.afi.com/images/afi-social.jpg">
                                    <link rel="icon" href="https://prdaficalmjediwestussa.blob.core.windows.net/images/2019/09/favicon.ico" type="image/png">
                 <!-- Google tag (gtag.js) -->
<script type="text/rocketlazyloadscript" async data-rocket-src="https://www.googletagmanager.com/gtag/js?id=G-WG5NKRT3RK"></script>
<script type="text/rocketlazyloadscript">
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-WG5NKRT3RK');
  gtag('config', 'UA-9824359-2');


 !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '404753177081502');
  fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=404753177081502&ev=PageView&noscript=1" /></noscript>
<script type="text/rocketlazyloadscript">
  // Get the current URL's search parameters
  const urlParams = new URLSearchParams(window.location.search);

  // Check if 'post_type' is NOT present
  if (!urlParams.has('post_type')) {

In [ ]:
#archive log response
for img in archive_soup.find_all("img"):
    src = img.get("src")
    # check if file path contains typical movie image folder naming
    if src and "wp-content/uploads" in src:
        print(src)

# not working, not printing anything so switching to selenium? https://selenium-python.readthedocs.io/$0

In [ ]:
#install
!apt-get update
!apt-get install -y chromium-chromedriver
!pip install selenium

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from bs4 import BeautifulSoup
import time

#configure the browser to run invisibly in the background
options = Options()
options.add_argument("--headless")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")
options.add_argument("user-agent=Mozilla/5.0")

driver = webdriver.Chrome(options=options)

#load the game page completely to let javascript finish running
driver.get("https://www.afi.com/get-the-picture/")
time.sleep(5)

#parse the fully loaded layout
live_soup = BeautifulSoup(driver.page_source, "html.parser")
driver.quit()

#print all text lines to isolate the real game choices
print(live_soup.get_text(separator="\n", strip=True))

In [ ]:
# find the hidden sub-window running the game code
for iframe in soup.find_all("iframe"):
    print(iframe.get("src"))

#https://www.googletagmanager.com/ns.html?id=GTM-PJLVF3W

https://www.googletagmanager.com/ns.html?id=GTM-PJLVF3W

In [ ]:
# target the full, exact link path to day 1000's image
image_url = "https://windows.net"
img_response = requests.get(image_url, headers={"User-Agent": "Mozilla/5.0"})

# check if the specific image file responds
print(img_response.status_code)

SSLError: HTTPSConnectionPool(host='windows.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'windows.net'. (_ssl.c:1032)")))

In [ ]:
# test matching game numbers to my email dates
test_games = {
    "015": {"year": "2022", "month": "04"},
    "1000": {"year": "2024", "month": "12"}
}

# Loop through test data to construct the full cloud addresses
for game_num, date_info in test_games.items():
    year = date_info["year"]
    month = date_info["month"]

    # Build complete path string
    full_url = f"https://prdaficalmjediwestussa.blob.core.windows.net/images/{year}/{month}/mc-gtp-{game_num}.webp"
    print(full_url)

https://prdaficalmjediwestussa.blob.core.windows.net/images/2022/04/mc-gtp-015.webp
https://prdaficalmjediwestussa.blob.core.windows.net/images/2024/12/mc-gtp-1000.webp

In [1]:
# test list to map game numbers to  email  dates
game_dates = [
    {"num": "015", "year": "2022", "month": "04"},
    {"num": "1000", "year": "2024", "month": "12"}
]

# loop through the map to generate the exact storage links
for game in game_dates:
    n = game["num"]
    y = game["year"]
    m = game["month"]

    url = f"https://prdaficalmjediwestussa.blob.core.windows.net/images/{y}/{m}/mc-gtp-{n}.webp"
    print(f"game {n} link: {url}")

game 015 link: https://prdaficalmjediwestussa.blob.core.windows.net/images/2022/04/mc-gtp-015.webp
game 1000 link: https://prdaficalmjediwestussa.blob.core.windows.net/images/2024/12/mc-gtp-1000.webp

In [2]:
# inspect day 1000 page code, to prepare to pull more info in scrape

import requests

# get raw webpage HTML for day 1000
response = requests.get("https://www.afi.com/movie-games/1000/")
print(response.text[:1000])  #the first 1000 characters

#got cloudflare warning, just try something eelsse

<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Attention Required! | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" /><![endif]-->
<style>body{margin:0;padding:0}</style>


<!--[if gte IE 10]><!-->
<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', f

In [6]:

!pip install cloudscraper

import cloudscraper

# Create a scraper instance
scraper = cloudscraper.create_scraper()

# Make the request exactly like  with 'requests'
url = "https://www.afi.com/get-the-picture/"
response = scraper.get(url)

print(response.text)

#got error, blob doesnt exist until changed to general game url then it pulled html and said rocket not webp

Requirement already satisfied: cloudscraper in /usr/local/lib/python3.13/dist-packages (1.2.71)
Requirement already satisfied: pyparsing>=2.4.7 in /usr/local/lib/python3.13/dist-packages (from cloudscraper) (3.3.2)
Requirement already satisfied: requests>=2.9.2 in /usr/local/lib/python3.13/dist-packages (from cloudscraper) (2.32.4)
Requirement already satisfied: requests-toolbelt>=0.9.1 in /usr/local/lib/python3.13/dist-packages (from cloudscraper) (1.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.9.2->cloudscraper) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.9.2->cloudscraper) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.9.2->cloudscraper) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.9.2->cloudscraper) (2026.7.22)
<!DOCTYPE html>
<html lang="en">
    <head><meta charset="UTF-8"><script>if(navigator.userAgent.match(/MSIE|Internet Explorer/i)||navigator.userAgent.match(/Trident\/7\..*?rv:11/i)){var href=document.location.href;if(!href.match(/[?&]nowprocket/)){if(href.indexOf("?")==-1){if(href.indexOf("#")==-1){document.location.href=href+"?nowprocket=1"}else{document.location.href=href.replace("#","?nowprocket=1#")}}else{if(href.indexOf("#")==-1){document.location.href=href+"&nowprocket=1"}else{document.location.href=href.replace("#","&nowprocket=1#")}}}}</script><script>(()=>{class RocketLazyLoadScripts{constructor(){this.v="2.0.5",this.userEvents=["keydown","keyup","mousedown","mouseup","mousemove","mouseover","mouseout","touchmove","touchstart","touchend","touchcancel","wheel","click","dblclick","input"],this.attributeEvents=["onblur","onclick","oncontextmenu","ondblclick","onfocus","onmousedown","onmouseenter","onmouseleave","onmousemove","onmouseout","onmouseover","onmouseup","onmousewheel","onscroll","onsubmit"]}async t(){this.i(),this.o(),/iP(ad|hone)/.test(navigator.userAgent)&&this.h(),this.u(),this.l(this),this.m(),this.k(this),this.p(this),this._(),await Promise.all([this.R(),this.L()]),this.lastBreath=Date.now(),this.S(this),this.P(),this.D(),this.O(),this.M(),await this.C(this.delayedScripts.normal),await this.C(this.delayedScripts.defer),await this.C(this.delayedScripts.async),await this.T(),await this.F(),await this.j(),await this.A(),window.dispatchEvent(new Event("rocket-allScriptsLoaded")),this.everythingLoaded=!0,this.lastTouchEnd&&await new Promise(t=>setTimeout(t,500-Date.now()+this.lastTouchEnd)),this.I(),this.H(),this.U(),this.W()}i(){this.CSPIssue=sessionStorage.getItem("rocketCSPIssue"),document.addEventListener("securitypolicyviolation",t=>{this.CSPIssue||"script-src-elem"!==t.violatedDirective||"data"!==t.blockedURI||(this.CSPIssue=!0,sessionStorage.setItem("rocketCSPIssue",!0))},{isRocket:!0})}o(){window.addEventListener("pageshow",t=>{this.persisted=t.persisted,this.realWindowLoadedFired=!0},{isRocket:!0}),window.addEventListener("pagehide",()=>{this.onFirstUserAction=null},{isRocket:!0})}h(){let t;function e(e){t=e}window.addEventListener("touchstart",e,{isRocket:!0}),window.addEventListener("touchend",function i(o){o.changedTouches[0]&&t.changedTouches[0]&&Math.abs(o.changedTouches[0].pageX-t.changedTouches[0].pageX)<10&&Math.abs(o.changedTouches[0].pageY-t.changedTouches[0].pageY)<10&&o.timeStamp-t.timeStamp<200&&(window.removeEventListener("touchstart",e,{isRocket:!0}),window.removeEventListener("touchend",i,{isRocket:!0}),"INPUT"===o.target.tagName&&"text"===o.target.type||(o.target.dispatchEvent(new TouchEvent("touchend",{target:o.target,bubbles:!0})),o.target.dispatchEvent(new MouseEvent("mouseover",{target:o.target,bubbles:!0})),o.target.dispatchEvent(new PointerEvent("click",{target:o.target,bubbles:!0,cancelable:!0,detail:1,clientX:o.changedTouches[0].clientX,clientY:o.changedTouches[0].clientY})),event.preventDefault()))},{isRocket:!0})}q(t){this.userActionTriggered||("mousemove"!==t.type||this.firstMousemoveIgnored?"keyup"===t.type||"mouseover"===t.type||"mouseout"===t.type||(this.userActionTriggered=!0,this.onFirstUserAction&&this.onFirstUserAction()):this.firstMousemoveIgnored=!0),"click"===t.type&&t.preventDefault(),t.stopPropagation(),t.stopImmediatePropagation(),"touchstart"===this.lastEvent&&"touchend"===t.type&&(this.lastTouchEnd=Date.now()),"click"===t.type&&(this.lastTouchEnd=0),this.lastEvent=t.type,t.composedPath&&t.composedPath()[0].getRootNode()instanceof ShadowRoot&&(t.rocketTarget=t.composedPath()[0]),this.savedUserEvents.push(t)}u(){this.savedUserEvents=[],this.userEventHandler=this.q.bind(this),this.userEvents.forEach(t=>window.addEventListener(t,this.userEventHandler,{passive:!1,isRocket:!0})),document.addEventListener("visibilitychange",this.userEventHandler,{isRocket:!0})}U(){this.userEvents.forEach(t=>window.removeEventListener(t,this.userEventHandler,{passive:!1,isRocket:!0})),document.removeEventListener("visibilitychange",this.userEventHandler,{isRocket:!0}),this.savedUserEvents.forEach(t=>{(t.rocketTarget||t.target).dispatchEvent(new window[t.constructor.name](t.type,t))})}m(){const t="return false",e=Array.from(this.attributeEvents,t=>"data-rocket-"+t),i="["+this.attributeEvents.join("],[")+"]",o="[data-rocket-"+this.attributeEvents.join("],[data-rocket-")+"]",s=(e,i,o)=>{o&&o!==t&&(e.setAttribute("data-rocket-"+i,o),e["rocket"+i]=new Function("event",o),e.setAttribute(i,t))};new MutationObserver(t=>{for(const n of t)"attributes"===n.type&&(n.attributeName.startsWith("data-rocket-")||this.everythingLoaded?n.attributeName.startsWith("data-rocket-")&&this.everythingLoaded&&this.N(n.target,n.attributeName.substring(12)):s(n.target,n.attributeName,n.target.getAttribute(n.attributeName))),"childList"===n.type&&n.addedNodes.forEach(t=>{if(t.nodeType===Node.ELEMENT_NODE)if(this.everythingLoaded)for(const i of[t,...t.querySelectorAll(o)])for(const t of i.getAttributeNames())e.includes(t)&&this.N(i,t.substring(12));else for(const e of[t,...t.querySelectorAll(i)])for(const t of e.getAttributeNames())this.attributeEvents.includes(t)&&s(e,t,e.getAttribute(t))})}).observe(document,{subtree:!0,childList:!0,attributeFilter:[...this.attributeEvents,...e]})}I(){this.attributeEvents.forEach(t=>{document.querySelectorAll("[data-rocket-"+t+"]").forEach(e=>{this.N(e,t)})})}N(t,e){const i=t.getAttribute("data-rocket-"+e);i&&(t.setAttribute(e,i),t.removeAttribute("data-rocket-"+e))}k(t){Object.defineProperty(HTMLElement.prototype,"onclick",{get(){return this.rocketonclick||null},set(e){this.rocketonclick=e,this.setAttribute(t.everythingLoaded?"onclick":"data-rocket-onclick","this.rocketonclick(event)")}})}S(t){function e(e,i){let o=e[i];e[i]=null,Object.defineProperty(e,i,{get:()=>o,set(s){t.everythingLoaded?o=s:e["rocket"+i]=o=s}})}e(document,"onreadystatechange"),e(window,"onload"),e(window,"onpageshow");try{Object.defineProperty(document,"readyState",{get:()=>t.rocketReadyState,set(e){t.rocketReadyState=e},configurable:!0}),document.readyState="loading"}catch(t){console.log("WPRocket DJE readyState conflict, bypassing")}}l(t){this.originalAddEventListener=EventTarget.prototype.addEventListener,this.originalRemoveEventListener=EventTarget.prototype.removeEventListener,this.savedEventListeners=[],EventTarget.prototype.addEventListener=function(e,i,o){o&&o.isRocket||!t.B(e,this)&&!t.userEvents.includes(e)||t.B(e,this)&&!t.userActionTriggered||e.startsWith("rocket-")||t.everythingLoaded?t.originalAddEventListener.call(this,e,i,o):(t.savedEventListeners.push({target:this,remove:!1,type:e,func:i,options:o}),"mouseenter"!==e&&"mouseleave"!==e||t.originalAddEventListener.call(this,e,t.savedUserEvents.push,o))},EventTarget.prototype.removeEventListener=function(e,i,o){o&&o.isRocket||!t.B(e,this)&&!t.userEvents.includes(e)||t.B(e,this)&&!t.userActionTriggered||e.startsWith("rocket-")||t.everythingLoaded?t.originalRemoveEventListener.call(this,e,i,o):t.savedEventListeners.push({target:this,remove:!0,type:e,func:i,options:o})}}J(t,e){this.savedEventListeners=this.savedEventListeners.filter(i=>{let o=i.type,s=i.target||window;return e!==o||t!==s||(this.B(o,s)&&(i.type="rocket-"+o),this.$(i),!1)})}H(){EventTarget.prototype.addEventListener=this.originalAddEventListener,EventTarget.prototype.removeEventListener=this.originalRemoveEventListener,this.savedEventListeners.forEach(t=>this.$(t))}$(t){t.remove?this.originalRemoveEventListener.call(t.target,t.type,t.func,t.options):this.originalAddEventListener.call(t.target,t.type,t.func,t.options)}p(t){let e;function i(e){return t.everythingLoaded?e:e.split(" ").map(t=>"load"===t||t.startsWith("load.")?"rocket-jquery-load":t).join(" ")}function o(o){function s(e){const s=o.fn[e];o.fn[e]=o.fn.init.prototype[e]=function(){return this[0]===window&&t.userActionTriggered&&("string"==typeof arguments[0]||arguments[0]instanceof String?arguments[0]=i(arguments[0]):"object"==typeof arguments[0]&&Object.keys(arguments[0]).forEach(t=>{const e=arguments[0][t];delete arguments[0][t],arguments[0][i(t)]=e})),s.apply(this,arguments),this}}if(o&&o.fn&&!t.allJQueries.includes(o)){const e={DOMContentLoaded:[],"rocket-DOMContentLoaded":[]};for(const t in e)document.addEventListener(t,()=>{e[t].forEach(t=>t())},{isRocket:!0});o.fn.ready=o.fn.init.prototype.ready=function(i){function s(){parseInt(o.fn.jquery)>2?setTimeout(()=>i.bind(document)(o)):i.bind(document)(o)}return"function"==typeof i&&(t.realDomReadyFired?!t.userActionTriggered||t.fauxDomReadyFired?s():e["rocket-DOMContentLoaded"].push(s):e.DOMContentLoaded.push(s)),this},s("on"),s("one"),s("off"),t.allJQueries.push(o)}e=o}t.allJQueries=[],o(window.jQuery),Object.defineProperty(window,"jQuery",{get:()=>e,set(t){o(t)}})}P(){const t=new Map;document.write=document.writeln=function(e){const i=document.currentScript,o=document.createRange(),s=i.parentElement;let n=t.get(i);void 0===n&&(n=i.nextSibling,t.set(i,n));const c=document.createDocumentFragment();o.setStart(c,0),c.appendChild(o.createContextualFragment(e)),s.insertBefore(c,n)}}async R(){return new Promise(t=>{this.userActionTriggered?t():this.onFirstUserAction=t})}async L(){return new Promise(t=>{document.addEventListener("DOMContentLoaded",()=>{this.realDomReadyFired=!0,t()},{isRocket:!0})})}async j(){return this.realWindowLoadedFired?Promise.resolve():new Promise(t=>{window.addEventListener("load",t,{isRocket:!0})})}M(){this.pendingScripts=[];this.scriptsMutationObserver=new MutationObserver(t=>{for(const e of t)e.addedNodes.forEach(t=>{"SCRIPT"!==t.tagName||!t.src||t.noModule||t.isWPRocket||this.pendingScripts.push({script:t,promise:new Promise(e=>{const i=()=>{const i=this.pendingScripts.findIndex(e=>e.script===t);i>=0&&this.pendingScripts.splice(i,1),e()};t.addEventListener("load",i,{isRocket:!0}),t.addEventListener("error",i,{isRocket:!0}),setTimeout(i,1e3)})})})}),this.scriptsMutationObserver.observe(document,{childList:!0,subtree:!0})}async F(){await this.X(),this.pendingScripts.length?(await this.pendingScripts[0].promise,await this.F()):this.scriptsMutationObserver.disconnect()}D(){this.delayedScripts={normal:[],async:[],defer:[]},document.querySelectorAll("script[type$=rocketlazyloadscript]").forEach(t=>{t.hasAttribute("data-rocket-src")?t.hasAttribute("async")&&!1!==t.async?this.delayedScripts.async.push(t):t.hasAttribute("defer")&&!1!==t.defer||"module"===t.getAttribute("data-rocket-type")?this.delayedScripts.defer.push(t):this.delayedScripts.normal.push(t):this.delayedScripts.normal.push(t)})}async _(){await this.L();let t=[];document.querySelectorAll("script[type$=rocketlazyloadscript][data-rocket-src]").forEach(e=>{let i=e.getAttribute("data-rocket-src");if(i&&!i.startsWith("data:")){i.startsWith("//")&&(i=location.protocol+i);try{const o=new URL(i).origin;o!==location.origin&&t.push({src:o,crossOrigin:e.crossOrigin||"module"===e.getAttribute("data-rocket-type")})}catch(t){}}}),t=[...new Map(t.map(t=>[JSON.stringify(t),t])).values()],this.Y(t,"preconnect")}async G(t){if(await this.K(),!0!==t.noModule||!("noModule"in HTMLScriptElement.prototype))return new Promise(e=>{let i;function o(){(i||t).setAttribute("data-rocket-status","executed"),e()}try{if(navigator.userAgent.includes("Firefox/")||""===navigator.vendor||this.CSPIssue)i=document.createElement("script"),[...t.attributes].forEach(t=>{let e=t.nodeName;"type"!==e&&("data-rocket-type"===e&&(e="type"),"data-rocket-src"===e&&(e="src"),i.setAttribute(e,t.nodeValue))}),t.text&&(i.text=t.text),t.nonce&&(i.nonce=t.nonce),i.hasAttribute("src")?(i.addEventListener("load",o,{isRocket:!0}),i.addEventListener("error",()=>{i.setAttribute("data-rocket-status","failed-network"),e()},{isRocket:!0}),setTimeout(()=>{i.isConnected||e()},1)):(i.text=t.text,o()),i.isWPRocket=!0,t.parentNode.replaceChild(i,t);else{const i=t.getAttribute("data-rocket-type"),s=t.getAttribute("data-rocket-src");i?(t.type=i,t.removeAttribute("data-rocket-type")):t.removeAttribute("type"),t.addEventListener("load",o,{isRocket:!0}),t.addEventListener("error",i=>{this.CSPIssue&&i.target.src.startsWith("data:")?(console.log("WPRocket: CSP fallback activated"),t.removeAttribute("src"),this.G(t).then(e)):(t.setAttribute("data-rocket-status","failed-network"),e())},{isRocket:!0}),s?(t.fetchPriority="high",t.removeAttribute("data-rocket-src"),t.src=s):t.src="data:text/javascript;base64,"+window.btoa(unescape(encodeURIComponent(t.text)))}}catch(i){t.setAttribute("data-rocket-status","failed-transform"),e()}});t.setAttribute("data-rocket-status","skipped")}async C(t){const e=t.shift();return e?(e.isConnected&&await this.G(e),this.C(t)):Promise.resolve()}O(){this.Y([...this.delayedScripts.normal,...this.delayedScripts.defer,...this.delayedScripts.async],"preload")}Y(t,e){this.trash=this.trash||[];let i=!0;var o=document.createDocumentFragment();t.forEach(t=>{const s=t.getAttribute&&t.getAttribute("data-rocket-src")||t.src;if(s&&!s.startsWith("data:")){const n=document.createElement("link");n.href=s,n.rel=e,"preconnect"!==e&&(n.as="script",n.fetchPriority=i?"high":"low"),t.getAttribute&&"module"===t.getAttribute("data-rocket-type")&&(n.crossOrigin=!0),t.crossOrigin&&(n.crossOrigin=t.crossOrigin),t.integrity&&(n.integrity=t.integrity),t.nonce&&(n.nonce=t.nonce),o.appendChild(n),this.trash.push(n),i=!1}}),document.head.appendChild(o)}W(){this.trash.forEach(t=>t.remove())}async T(){try{document.readyState="interactive"}catch(t){}this.fauxDomReadyFired=!0;try{await this.K(),this.J(document,"readystatechange"),document.dispatchEvent(new Event("rocket-readystatechange")),await this.K(),document.rocketonreadystatechange&&document.rocketonreadystatechange(),await this.K(),this.J(document,"DOMContentLoaded"),document.dispatchEvent(new Event("rocket-DOMContentLoaded")),await this.K(),this.J(window,"DOMContentLoaded"),window.dispatchEvent(new Event("rocket-DOMContentLoaded"))}catch(t){console.error(t)}}async A(){try{document.readyState="complete"}catch(t){}try{await this.K(),this.J(document,"readystatechange"),document.dispatchEvent(new Event("rocket-readystatechange")),await this.K(),document.rocketonreadystatechange&&document.rocketonreadystatechange(),await this.K(),this.J(window,"load"),window.dispatchEvent(new Event("rocket-load")),await this.K(),window.rocketonload&&window.rocketonload(),await this.K(),this.allJQueries.forEach(t=>t(window).trigger("rocket-jquery-load")),await this.K(),this.J(window,"pageshow");const t=new Event("rocket-pageshow");t.persisted=this.persisted,window.dispatchEvent(t),await this.K(),window.rocketonpageshow&&window.rocketonpageshow({persisted:this.persisted})}catch(t){console.error(t)}}async K(){Date.now()-this.lastBreath>45&&(await this.X(),this.lastBreath=Date.now())}async X(){return document.hidden?new Promise(t=>setTimeout(t)):new Promise(t=>requestAnimationFrame(t))}B(t,e=window){return e===document&&"readystatechange"===t||(e===document&&"DOMContentLoaded"===t||(e===window&&"DOMContentLoaded"===t||(e===window&&"load"===t||e===window&&"pageshow"===t)))}static run(){(new RocketLazyLoadScripts).t()}}RocketLazyLoadScripts.run()})();
</script>

        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>
		Get The Picture - AFI's daily movie guessing game | American Film Institute
		</title>
<link data-rocket-prefetch href="https://use.typekit.net" rel="dns-prefetch">
<link data-rocket-prefetch href="https://cdnjs.cloudflare.com" rel="dns-prefetch">
<link data-rocket-prefetch href="https://challenges.cloudflare.com" rel="dns-prefetch"><link rel="preload" data-rocket-preload as="image" href="https://www.afi.com/wp-content/plugins/movie-game/images/gtp-header-background.webp" fetchpriority="high">
		<meta name="description" content="AFI’s Get the Picture is a daily movie guessing game for you to test your movie knowledge by identifying a film from just one image. Can you Get the Picture?" />
				<meta property="og:title" content="get-the-picture"/>
						<meta name="robots" content="index" />
				<meta http-equiv="Content-Type" content="text/html" />
		<meta name="twitter:card" content="summary_large_image" />

		<meta data-n-head="ssr" data-hid="og:image:type" property="og:image:type" content="image/jpeg">
		<meta property="og:locale" content="en_US" />
		<meta property="og:site_name" content="American Film Institute" />
		<meta property="og:type" content="article" />
		<meta property="og:title" content="Get The Picture - AFI's daily movie guessing game | American Film Institute" />
		<meta property="og:url" content="https://www.afi.com/get-the-picture/" />
		<meta name="twitter:card" content="summary_large_image" />
		<meta name="twitter:site" content="American Film Institute" />
		<meta name="twitter:title" content="Get The Picture - AFI's daily movie guessing game | American Film Institute" />
		<meta name="twitter:description" content="AFI’s Get the Picture is a daily movie guessing game for you to test your movie knowledge by identifying a film from just one image. Can you Get the Picture?" />
		<meta name="twitter:creator" content="@afifilm" />
		<meta property="og:image:width" content="1200" />
		<meta property="og:image:height" content="630" />


                	    <meta property="og:image" content="https://prdaficalmjediwestussa.blob.core.windows.net/images/2023/08/gtp-social.png">
        <meta name="twitter:image" content="https://prdaficalmjediwestussa.blob.core.windows.net/images/2023/08/gtp-social.png">
        <meta property="og:description" content="Go to AFI.com/get-the-picture to play Get the Picture!">
                                    <link rel="icon" href="https://prdaficalmjediwestussa.blob.core.windows.net/images/2019/09/favicon.ico" type="image/png">
                 <!-- Google tag (gtag.js) -->
<script type="text/rocketlazyloadscript" async data-rocket-src="https://www.googletagmanager.com/gtag/js?id=G-WG5NKRT3RK"></script>
<script type="text/rocketlazyloadscript">
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-WG5NKRT3RK');
  gtag('config', 'UA-9824359-2');


 !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '404753177081502');
  fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=404753177081502&ev=PageView&noscript=1" /></noscript>
<script type="text/rocketlazyloadscript">
  // Get the current URL's search parameters
  const urlParams = new URLSearchParams(window.location.search);

  // Check if 'post_type' is NOT present

In [7]:
!pip install cloudscraper beautifulsoup4


import cloudscraper
from bs4 import BeautifulSoup

#url to scrape
URL = "https://www.afi.com/get-the-picture/"

def get_data(target_url):
    #  tricks Cloudflare that a Chrome browser on Windows
    scraper = cloudscraper.create_scraper(
        browser={
            'browser': 'chrome',
            'platform': 'windows',
            'desktop': True
        }
    )

    try:
        response = scraper.get(target_url)
        # if page loads fine, hands it to BeautifulSoup
        if response.status_code == 200:
            return BeautifulSoup(response.text, 'html.parser')
        else:
            print(f"Error Status code: {response.status_code}")
            return None
    except Exception as e:
        print(f"Something went wrong with the request: {e}")
        return None

# START scraper
soup = get_data(URL)

# check to see if actually got the HTML back
if soup:
    print(soup.prettify()[:500])

Requirement already satisfied: cloudscraper in /usr/local/lib/python3.13/dist-packages (1.2.71)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.13/dist-packages (4.13.5)
Requirement already satisfied: pyparsing>=2.4.7 in /usr/local/lib/python3.13/dist-packages (from cloudscraper) (3.3.2)
Requirement already satisfied: requests>=2.9.2 in /usr/local/lib/python3.13/dist-packages (from cloudscraper) (2.32.4)
Requirement already satisfied: requests-toolbelt>=0.9.1 in /usr/local/lib/python3.13/dist-packages (from cloudscraper) (1.0.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.9.2->cloudscraper) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.9.2->cloudscraper) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.9.2->cloudscraper) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.9.2->cloudscraper) (2026.7.22)
<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <script type="text/javascript">
   (window.NREUM||(NREUM={})).init={privacy:{cookies_enabled:true},ajax:{deny_list:["bam.nr-data.net"]},distributed_tracing:{enabled:true}};(window.NREUM||(NREUM={})).loader_config={agentID:"1103240418",accountID:"3934328",trustKey:"66686",xpid:"Vw8EVVVRABABVFBaAgkPVlwF",licenseKey:"NRJS-93da15506e488dba2c8",applicationID:"1018588084",browserID:"1103240418"};;/*! For license information please se

In [11]:

!pip install cloudscraper beautifulsoup4 pandas


import cloudscraper
from bs4 import BeautifulSoup
import pandas as pd
import time

URLS_TO_SCRAPE = ["https://www.afi.com/movie-games/508/"]

def scrape_afi_game_with_meta(url):
    scraper = cloudscraper.create_scraper(
        browser={
            'browser': 'chrome',
            'platform': 'windows',
            'desktop': True
        }
    )

    try:
        response = scraper.get(url)
        if response.status_code != 200:
            print(f"Skipping {url} (Status: {response.status_code})")
            return None

        soup = BeautifulSoup(response.text, 'html.parser')


        # Finding the game number from "Guess the movie (#508)
        game_title_element = soup.find('h2', class_='game-title') or soup.find('h1')
        game_title_text = game_title_element.text.strip() if game_title_element else ""

        # Finding the publish date/time if in   meta data
        date_element = soup.find('meta', property='article:published_time') or soup.find('time')
        # Checks if it can pull from  string, otherwise grabs the text
        game_date_time = date_element.get('content') or date_element.text.strip() if date_element else "Missing Date"

        # image pull line
        image_tag = soup.find('img', class_='game-image') or soup.find('div', class_='game-container').find('img')
        image_url = image_tag['src'] if image_tag else "Missing Image"

        incorrect_answers = []
        correct_answer = None
        user_percentages = {}

        options = soup.find_all('li', class_='game-option') or soup.find_all('div', class_='answer-option')

        for option in options:
            text_element = option.find('span', class_='option-text') or option
            answer_text = text_element.text.replace('\n', '').strip()

            pct_element = option.find('span', class_='vote-percentage') or option.find('span', class_='percent')
            pct_value = pct_element.text.strip() if pct_element else "0%"
            user_percentages[answer_text] = pct_value

            classes = option.get('class', [])
            is_correct = 'is-correct' in classes or 'correct' in classes or option.get('data-correct') == 'true'

            if is_correct:
                correct_answer = answer_text
            else:
                incorrect_answers.append(answer_text)

        # Packaging fields into the dictionary data row
        return {
            "game_header": game_title_text,
            "date_time_stamp": game_date_time,
            "source_url": url,
            "movie_image_url": image_url,
            "correct_answer": correct_answer,
            "incorrect_answers": incorrect_answers,
            "all_percentages": user_percentages
        }

    except Exception as e:
        print(f"Error handling URL {url}: {str(e)}")
        return None

# Loop execution
dataset = []
for target in URLS_TO_SCRAPE:
    data = scrape_afi_game_with_meta(target)
    if data:
        dataset.append(data)
    #wait 2 secs
    time.sleep(2)

df = pd.DataFrame(dataset)
df.head()

#error nonetype object

Requirement already satisfied: cloudscraper in /usr/local/lib/python3.13/dist-packages (1.2.71)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.13/dist-packages (4.13.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: pyparsing>=2.4.7 in /usr/local/lib/python3.13/dist-packages (from cloudscraper) (3.3.2)
Requirement already satisfied: requests>=2.9.2 in /usr/local/lib/python3.13/dist-packages (from cloudscraper) (2.32.4)
Requirement already satisfied: requests-toolbelt>=0.9.1 in /usr/local/lib/python3.13/dist-packages (from cloudscraper) (1.0.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (4.16.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.9.2->cloudscraper) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.9.2->cloudscraper) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.9.2->cloudscraper) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.9.2->cloudscraper) (2026.7.22)
ERROR: Operation cancelled by user
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/cli/base_command.py", line 179, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/commands/install.py", line 447, in run
    conflicts = self._determine_conflicts(to_install)
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/commands/install.py", line 578, in _determine_conflicts
    return check_install_conflicts(to_install)
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/operations/check.py", line 101, in check_install_conflicts
    package_set, _ = create_package_set_from_installed()
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/operations/check.py", line 42, in create_package_set_from_installed
    dependencies = list(dist.iter_dependencies())
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/metadata/importlib/_dists.py", line 222, in iter_dependencies
    req = Requirement(req_string.strip())
  File "/usr/local/lib/python3.13/dist-packages/pip/_vendor/packaging/requirements.py", line 43, in __init__
    self.specifier: SpecifierSet = SpecifierSet(parsed.specifier)
                                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/pip/_vendor/packaging/specifiers.py", line 718, in __init__
    self._specs = frozenset(map(Specifier, split_specifiers))
                  ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/pip/_vendor/packaging/specifiers.py", line 331, in __hash__
    return hash(self._canonical_spec)
                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/pip/_vendor/packaging/specifiers.py", line 324, in _canonical_spec
    canonical_version = canonicalize_version(
        self._spec[1],
        strip_trailing_zero=(self._spec[0] != "~="),
    )
  File "/usr/local/lib/python3.13/dist-packages/pip/_vendor/packaging/utils.py", line 66, in canonicalize_version
    parsed = Version(version)
  File "/usr/local/lib/python3.13/dist-packages/pip/_vendor/packaging/version.py", line 207, in __init__
    release=tuple(int(i) for i in match.group("release").split(".")),
                                  ~~~~~~~~~~~^^^^^^^^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 10, in <module>
    sys.exit(main())
             ~~~~^^
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/cli/main.py", line 80, in main
    return command.main(cmd_args)
           ~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/cli/base_command.py", line 100, in main
    return self._main(args)
           ~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/cli/base_command.py", line 232, in _main
    return run(options, args)
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/cli/base_command.py", line 216, in exc_logging_wrapper
    logger.debug("Exception information:", exc_info=True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 1508, in debug
    self._log(DEBUG, msg, args, **kwargs)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 1665, in _log
    self.handle(record)
    ~~~~~~~~~~~^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 1681, in handle
    self.callHandlers(record)
    ~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 1741, in callHandlers
    hdlr.handle(record)
    ~~~~~~~~~~~^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 1027, in handle
    self.emit(record)
    ~~~~~~~~~^^^^^^^^
  File "/usr/lib/python3.13/logging/handlers.py", line 81, in emit
    logging.FileHandler.emit(self, record)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 1265, in emit
    StreamHandler.emit(self, record)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 1151, in emit
    msg = self.format(record)
  File "/usr/lib/python3.13/logging/__init__.py", line 999, in format
    return fmt.format(record)
           ~~~~~~~~~~^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/utils/logging.py", line 112, in format
    formatted = super().format(record)
  File "/usr/lib/python3.13/logging/__init__.py", line 720, in format
    record.exc_text = self.formatException(record.exc_info)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 670, in formatException
    traceback.print_exception(ei[0], ei[1], tb, limit=None, file=sio)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/traceback.py", line 129, in print_exception
    te = TracebackException(type(value), value, tb, limit=limit, compact=True)
  File "/usr/lib/python3.13/traceback.py", line 1051, in __init__
    self.stack = StackSummary._extract_from_extended_frame_gen(
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        _walk_tb_with_full_positions(exc_traceback),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        limit=limit, lookup_lines=lookup_lines,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        capture_locals=capture_locals)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/traceback.py", line 475, in _extract_from_extended_frame_gen
    for f, (lineno, end_lineno, colno, end_colno) in frame_gen:
                                                     ^^^^^^^^^
  File "/usr/lib/python3.13/traceback.py", line 407, in _walk_tb_with_full_positions
    positions = _get_code_position(tb.tb_frame.f_code, tb.tb_lasti)
  File "/usr/lib/python3.13/traceback.py", line 420, in _get_code_position
    positions_gen = code.co_positions()
KeyboardInterrupt
^C
Error handling URL https://www.afi.com/movie-games/508/: 'NoneType' object has no attribute 'find'

Empty DataFrame
Columns: []
Index: []

In [12]:
import cloudscraper
from bs4 import BeautifulSoup
import pandas as pd
import time

start_day = 508
end_day = 508

def scrape_afi_game(day_number):
    url = f"https://afi.com{day_number}/"

    scraper = cloudscraper.create_scraper(
        browser={'browser': 'chrome', 'platform': 'windows', 'desktop': True}
    )

    try:
        response = scraper.get(url)
        if response.status_code != 200:
            return None

        soup = BeautifulSoup(response.text, 'html.parser')

        # pull heading text
        header_tag = soup.find('h4')
        game_title = header_tag.text.strip() if header_tag else f"game #{day_number}"

        # extract film answer paths
        choices = []
        if header_tag:
            options_list = header_tag.find_next('ul') or header_tag.find_next('ol')
            if options_list:
                choices = [li.text.strip() for li in options_list.find_all('li')]

        # trace movie snap link strings
        image_url = "no image found"

        # check parent wrappers
        image_container = soup.find('div', class_='game-container') or soup.find('div', class_='wp-block-image')
        if image_container:
            img_tag = image_container.find('img')
            if img_tag and img_tag.get('src'):
                image_url = img_tag['src']

        # scan layout tags if blocks miss it
        if image_url == "no image found":
            for img in soup.find_all('img'):
                src = img.get('src', '')
                if any(keyword in src for keyword in ['wp-content', 'movie-games', 'get-the-picture']):
                    image_url = src
                    break

        return {
            "game_number": day_number,
            "title_text": game_title,
            "image_link": image_url,
            "choices": choices,
            "url": url
        }
    except Exception as e:
        print(f"skipped day {day_number} due to error {e}")
        return None

# run collection engine loops
dataset = []
for day in range(start_day, end_day + 1):
    print(f"scraping day {day}")
    data = scrape_afi_game(day)
    if data:
        dataset.append(data)
    time.sleep(1)

# print dataset matrices out
df = pd.DataFrame(dataset)
df.head()


# ran skipped day 508 due to error

scraping day 508
skipped day 508 due to error HTTPSConnectionPool(host='afi.com508', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7e61ac877890>: Failed to resolve 'afi.com508' ([Errno -2] Name or service not known)"))

Empty DataFrame
Columns: []
Index: []

In [14]:
import cloudscraper
from bs4 import BeautifulSoup
import pandas as pd
import time

start_day = 508
end_day = 508

def scrape_afi_game(day_number):
    # build the path carefully so it dont smash the link together wrong
    base_url = "https://afi.com"
    url = base_url + str(day_number) + "/"

    scraper = cloudscraper.create_scraper(
        browser={'browser': 'chrome', 'platform': 'windows', 'desktop': True}
    )

    try:
        response = scraper.get(url)
        if response.status_code != 200:
            return None

        soup = BeautifulSoup(response.text, 'html.parser')

        # pull heading text shrug
        header_tag = soup.find('h4')
        game_title = header_tag.text.strip() if header_tag else "guess game missing text"

        # extract film answer paths from lists
        choices = []
        if header_tag:
            options_list = header_tag.find_next('ul') or header_tag.find_next('ol')
            if options_list:
                choices = [li.text.strip() for li in options_list.find_all('li')]

        # trace movie snap link strings for photos
        image_url = "no image found"

        # check parent wrappers around the image layout
        image_container = soup.find('div', class_='game-container') or soup.find('div', class_='wp-block-image')
        if image_container:
            img_tag = image_container.find('img')
            if img_tag and img_tag.get('src'):
                image_url = img_tag['src']

        # scan layout tags if blocks miss it completely
        if image_url == "no image found":
            for img in soup.find_all('img'):
                src = img.get('src', '')
                if any(keyword in src for keyword in ['wp-content', 'movie-games', 'get-the-picture']):
                    image_url = src
                    break

        return {
            "game_number": day_number,
            "title_text": game_title,
            "image_link": image_url,
            "choices": choices,
            "url": url
        }
    except Exception as e:
        print(f"skipped day due to error")
        return None

# run collection engine loops over the days
dataset = []
for day in range(start_day, end_day + 1):
    print(f"scraping day {day}")
    data = scrape_afi_game(day)
    if data:
        dataset.append(data)
    time.sleep(1)

# print dataset matrices out into colab layout
df = pd.DataFrame(dataset)
df.head()


# ran had error

scraping day 508
skipped day due to error

Empty DataFrame
Columns: []
Index: []

In [15]:
import requests
import cloudscraper
from bs4 import BeautifulSoup
import pandas as pd
import time

start_day = 508
end_day = 508

def scrape_afi_game(day_number):
    base_url = "https://www.afi.com/movie-games/"
    url = base_url + str(day_number) + "/"

    # try cloudscraper first to slide past firewalls
    try:
        scraper = cloudscraper.create_scraper(
            browser={'browser': 'chrome', 'platform': 'windows', 'desktop': True}
        )
        response = scraper.get(url, timeout=10)
    except Exception:
        # fallback to standard requests if scraper crashes out completely
        try:
            headers = {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
            }
            response = requests.get(url, headers=headers, timeout=10)
        except Exception as e:
            print(f"network link broke down totally {e}")
            return None

    if response.status_code != 200:
        print(f"site rejected the request status code is {response.status_code}")
        return None

    try:
        soup = BeautifulSoup(response.text, 'html.parser')

        # hunt down the game text title element
        header_tag = soup.find('h4')
        game_title = header_tag.text.strip() if header_tag else "guess game missing text"

        # pull the options from list blocks below heading
        choices = []
        if header_tag:
            options_list = header_tag.find_next('ul') or header_tag.find_next('ol')
            if options_list:
                choices = [li.text.strip() for li in options_list.find_all('li')]

        # track image source paths for the film shot
        image_url = "no image found"
        image_container = soup.find('div', class_='game-container') or soup.find('div', class_='wp-block-image')
        if image_container:
            img_tag = image_container.find('img')
            if img_tag and img_tag.get('src'):
                image_url = img_tag['src']

        # grab raw layout sources if container blocks miss it
        if image_url == "no image found":
            for img in soup.find_all('img'):
                src = img.get('src', '')
                if any(keyword in src for keyword in ['wp-content', 'movie-games', 'get-the-picture']):
                    image_url = src
                    break

        return {
            "game_number": day_number,
            "title_text": game_title,
            "image_link": image_url,
            "choices": choices,
            "url": url
        }
    except Exception as e:
        print(f"parsing error messed up layout processing {e}")
        return None

# run collection engine loops over the days
dataset = []
for day in range(start_day, end_day + 1):
    print(f"scraping day {day}")
    data = scrape_afi_game(day)
    if data:
        dataset.append(data)
    time.sleep(1)

# print dataset matrices out into colab layout
df = pd.DataFrame(dataset)
df.head()

scraping day 508

,game_number,title_text,image_link,choices,url
0,508,Guess the movie (#508):,/wp-content/themes/AFI/images/white_search.png,"[ALL OF ME, BIG BUSINESS, RUTHLESS PEOPLE, SIS...",https://www.afi.com/movie-games/508/